name: Cron

on:
  schedule:
    - cron:  0 0 * * 1

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: true
      matrix:
        cfengine: ["lucee@5", "adobe@2016", "adobe@2018", "adobe@2021"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start containers
        env:
          BOX_INSTALL: true
          BOX_SERVER_APP_CFENGINE: ${{ matrix.cfengine }}
        run: |
          docker-compose up -d --build
          sleep 5 # this is because the unleash server tends to fail the first time for some reason
          docker-compose up -d --build

      - name: Run TestBox Tests
        run: docker-compose exec -T sdk box testbox run