name: PRs and Branches

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: true
      matrix:
        cfengine: ["lucee@5", "adobe@2016", "adobe@2018", "adobe@2021"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start containers
        env:
          BOX_INSTALL: true
          BOX_SERVER_APP_CFENGINE: ${{ matrix.cfengine }}
        run: |
          docker-compose up -d --build
          sleep 5 # this is because the unleash server tends to fail the first time for some reason
          docker-compose up -d --build
          sleep 30 # wait for the server to start

      - name: Run TestBox Tests
        run: docker-compose exec -T sdk box testbox run

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11 

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0
      
      - name: Install CFFormat
        run: box install commandbox-cfformat
      
      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes